### ISSUE TITLE
Won't pull images from cache.

### ISSUE THREAD

**Issue by Joethelazy1** [eight04/image-picka#267]
Hello,
Great extension first of all! It has saved me countless hours over time in my work, almost custom made for it, so I appreciate your time.
 I'm having an issue in which I can't get Image Picka to save images from cache. I do have the option checked in the config page, but after opening each image in it's own tab, which means it's already downloaded, when I click save the extension re-downloads all the images again.
 I did an experiment where I cleared the total cache in Firefox and opened the empty folder. When I open each image in it's own tab, I can see the entry entered in the cache folder. When I click save, Image Picka re-downloads the pictures and adds it's own entry in the cache. If I leave the tabs open and click save again the the process happens almost immediately, so then I know that it obviously is saving the image from cache at that point. It's almost like there's a naming difference in which Image Picka can't recognize that the image entries in the cache file are the same entries that it is looking to save. Then, after you run save once and it re-downloads the pictures and creates it's own entries in the cache file, if you run save again it CAN recognize the entries and it pulls the images from cache in practically no time. It's possible I have a setting wrong or something, but I can't figure it out. Can you please help with this?
Thank you.

**Comment by eight04** [comment]
The main problem is that browsers started isolating each page to its own origin and the ability to hit the same cached entry is more restricted.

Currently, Firefox will try to use the cache when the download manager receives a URL. To make it happen, you have to check *off* `download from browser cache` option in Image Picka so it sends the raw URL to the download manager directly. I don't know how reliable is it and it will *not* work with batch download since batch download fetches all images to the extension page and display them.

IMO the most reliable solution is to make Firefox provide a cache API so the extension can interact with all cached entries directly.

More information:
#251
https://bugzilla.mozilla.org/show_bug.cgi?id=1691907
https://bugzilla.mozilla.org/show_bug.cgi?id=1670278
https://github.com/eight04/webext-hit-the-cache

**Comment by Joethelazy1** [comment]
Thank you, explained very well. I'm not a programmer or anything close to one, but I'll try to find out how to relay the inf.

Thanks again!
________________________________
