### ISSUE TITLE
wait 0.15.0

### ISSUE THREAD

**Issue by tenjouina** [eight04/image-picka#275]
どうゆう設定をすればいいのでしょうか？
retry on failurlに「https://t\.i9i9\.to/.*」を入力しても従来と変わらないんですが
![キャプチャ](https://user-images.githubusercontent.com/87722942/140608303-973d511f-7b04-4008-8ab6-ec085606e4d6.JPG)

**Comment by eight04** [comment]
Maybe the regex doesn't match the URL.

Move the cursor onto a red square and it should show the URL which failed fetching. Take a screenshot and let's see if it matches the regex.

**Comment by tenjouina** [comment]
![無題](https://user-images.githubusercontent.com/87722942/140612850-d5341963-d488-4035-ab2c-5297eee83671.png)
以前これだと思いますと言われた「https://t￥.i9i9￥.to/.*　10 5 1.2」を入力してます

**Comment by eight04** [comment]
I think there are two issues:

1. The regex in [this comment](https://github.com/eight04/image-picka/issues/272#issuecomment-957183814) is wrong. It should be `i.i9i9.to` instead of `t.i9i9.to`
2. It still make large traffic to the site at one time. We need a setting to limit the number of images fetched at once.
