### ISSUE TITLE
[Feature Request] Click thumbnail to switch to tab

### ISSUE THREAD

**Issue by brazenvoid** [eight04/image-picka#358]
I have this problem that an image board I browse frequently has issues with image delivery, thus, some images always fail when I do a pick across tabs. 

As there is no way currently to switch to the tab the image is located, I have to work a lot to locate and refresh that specific tab.

So if this switch to image tab function can be added to the thumbnail of the image in the browser view, it will make my work very easy.

**Comment by eight04** [comment]
This is technically possible. But I think we need a better UX. Switch tabs when clicking on the image is kind of confusing. It also conflicts with the current behavior - toggle the selection.

There is an "Isolate tabs" option, which will group images in the same tab. I think we can add a switch tab button to the title of the group.

When "Isolate tabs" is not checked, we can probably add a context menu command?

The command could be "Show the source element". When clicked, switch the tab and scroll the page to the image.

---

BTW we should hide those "Pick images..." context menu commands in the picker since it makes no sense.

**Comment by eight04** [comment]
BTW have you tried the retry-on-failure feature?
https://github.com/eight04/image-picka?tab=readme-ov-file#retry-on-failure

**Comment by brazenvoid** [comment]
Ok I'll try the retry rules feature. As for the feature request, yes, context menu option is fine.

**Comment by brazenvoid** [comment]
> BTW have you tried the retry-on-failure feature? https://github.com/eight04/image-picka?tab=readme-ov-file#retry-on-failure

Naah it won't work for that site as they have a distributed image distribution system, there are thousands of peers and the domains are dynamic unless of course the rule can accommodate wildcard for everything.

**Comment by brazenvoid** [comment]
@eight04 It doesn't work for the case I wanted it for, failed images, No option is presented in the context money for such,

**Comment by eight04** [comment]
Hmm we don't display thumbnails for failure images.

I think we just have to give thumbnails a minimal width/height and set the default src to `about:blank`.
