### ISSUE TITLE
Does not execlude secured domains

### ISSUE THREAD

**Issue by ksadom** [eight04/image-picka#51]
Hi eight04,
The excluding option seems that not exclude domain that start with https (secured url) for example:
https://www.aliexpress.com

**Comment by eight04** [comment]
Well, I think the problem is *not* about HTTPS but that website uses individual domains like:
```
www.aliexpress.com
sale.aliexpress.com
riinr.aliexpress.com
```
If you add all of them to exclusion then it should work. Actually, I think we should introduce a new syntax to match sub-domain. For example, if you add following to the exclusion:
```
*.aliexpress.com
```
Then every domain ending with `aliexpress.com` would be excluded.

**Comment by ksadom** [comment]
> f you add all of them to exclusion then it should work. Actually, I think we should introduce a new syntax to match sub-domain. For example, if you add following to the exclusion:
*.aliexpress.com

This is better way. Thank you for your support.

**Comment by eight04** [comment]
Added in 0.7.0.
